modified:   README 	modified:   achoo 	new file:   achoodesktop 	modified:   achoofuncs 	modified:   achoovariables 	modified:   testbed

diff --git a/achoo b/achoo
--- a/achoo
+++ b/achoo
@@ -5,8 +5,8 @@
 # Developed by Elizabeth Mills, incorporating some code adapted from the
 # excellent Evo/Lution script by Carl Duff and AUI scripts by HelmuthDU.
 
-# The achoovariables and achoofuncs scripts must be present in the same
-# directory when running this script.
+# The achoovariables, achoodesktop and achoofuncs scripts must be
+# present in the same directory when running this script.
 
 # The Achoo! scripts are still in development, and may contain bugs. They
 # were originally written for my own use, but are shared in the spirit of
@@ -35,11 +35,19 @@ else
   exit 1
 fi
 
+if [[ -f `pwd`/achoodesktop ]]; then
+  source achoodesktop
+else
+  echo "missing file: achoodesktop"
+  exit 1
+fi
+
 # Test internet connection
 CheckInternet
 StartTime=$(date +%s)
 
-# Check partitioning, offer cfdisk
+# Check partition table and partitions, offer cfdisk
+TestUEFI
 ManagePartitions
 # Display partitions and allocate root
 
@@ -164,11 +172,10 @@ TPecho "Setting clock"
 arch_chroot "ln -sf /usr/share/zoneinfo/${ZONE}/${SUBZONE} /etc/localtime"
 arch_chroot "hwclock --systohc --utc"
 
-TPecho "Enabling dhcpcd"
-arch_chroot "systemctl enable dhcpcd.service"
-
 if [ $Scope = "Full" ] || [ $Scope = "Extras" ]
 then
+  TPecho "Enabling dhcpcd"
+  arch_chroot "systemctl enable dhcpcd.service"
   TPecho "Installing and configuring network services"
   pacstrap /mnt networkmanager network-manager-applet rp-pppoe 2> error.log
   CheckForError "${LINENO} 'Installing network manager'" 2
@@ -193,9 +200,19 @@ arch_chroot "mkinitcpio -p linux-lts"
 echo KEYMAP=${Countrykbd} > /mnt/etc/vconsole.conf 2> error.log
 CheckForError "${LINENO} 'Saving persistent keymap'" 1
 
-# Required for Virtualbox installations
-echo blacklist i2c_piix4 > /mnt/etc/modprobe.d/modprobe.conf 2> error.log
-CheckForError "${LINENO} 'vbox piix4 override'" 1
+# Use dmidecode to check for Virtualbox installation
+# pacman -S --noconfirm -q dmidecode 2> error.log
+# CheckForError "${LINENO} 'Installing dmidecode'" 2
+IsInVbox=`dmidecode --type 1 | grep VirtualBox`
+if [[ -z ${IsInVbox} ]]; then
+  pacstrap /mnt xf86-video-vesa xf86-video-nouveau 2> error.log
+else
+  # Add code to overcome piix4 Virtualbox error
+  echo blacklist i2c_piix4 > /mnt/etc/modprobe.d/modprobe.conf 2> error.log
+  CheckForError "${LINENO} 'vbox piix4 override'" 1
+  # Install Virtualbox video modules
+  pacstrap /mnt virtualbox-guest-modules virtualbox-guest-utils virtualbox-guest-dkms
+fi
 
 # Extra processes for 'Full' or 'Extras' installation
 if [ $Scope = "Full" ] || [ $Scope = "Extras" ]
@@ -228,18 +245,29 @@ then
   pacstrap /mnt iw wireless_tools wpa_actiond wpa_supplicant dialog 2> error.log
   CheckForError "${LINENO} 'Wireless tools'" 1
 
-  # Install X, graphics, etc
+  # Install X, graphics, Virtualbox guest modules, etc
   TPecho "Installing X, graphics, etc"
-  pacstrap /mnt xorg-server  xorg-server-utils xorg-apps xorg-xinit xorg-twm xf86-video-vesa xf86-video-nouveau 2> error.log
+  pacstrap /mnt xorg-server  xorg-server-utils xorg-apps xorg-xinit xorg-twm 2> error.log
   CheckForError "${LINENO} 'Installing X, Graphics, etc'" 1
+  if [[ -z ${IsInVbox} ]]; then
+    pacstrap /mnt xf86-video-vesa xf86-video-nouveau 2> error.log
+    CheckForError "${LINENO} 'Installing nouveau'" 1
+  else
+    # Add code to overcome piix4 Virtualbox error
+    echo blacklist i2c_piix4 > /mnt/etc/modprobe.d/modprobe.conf 2> error.log
+    CheckForError "${LINENO} 'vbox piix4 override'" 1
+    # Install Virtualbox video modules
+    pacstrap /mnt virtualbox-guest-modules virtualbox-guest-utils virtualbox-guest-dkms
+    CheckForError "${LINENO} 'Installing Virtualbox guest modules'" 1
+  fi
 
   # Copy modified pacman.conf to new system and install Yaourt
   TPecho "Modifying pacman.conf and installing Yaourt"
-  cp pacman.conf /mnt/etc 2> error.log
+  cp pacman.conf /mnt/etc 2> error.log # For installed system
   CheckForError "${LINENO} 'Copying pacman.conf MOUNTPOINT'" 1
-  cp pacman.conf /etc 2> error.log
+  cp pacman.conf /etc 2> error.log # For installer
   CheckForError "${LINENO} 'Copying pacman.conf local'" 1
-  pacman -Sy 2> error.log
+  pacman -Sy 2> error.log # Update
   CheckForError "${LINENO} 'Update Arch" 1
   pacstrap /mnt yaourt 2> error.log
   CheckForError "${LINENO} 'Install yaourt'" 1
@@ -285,7 +313,7 @@ then
         CheckForError "Line ${LINENO} 'Installing lxde'" 1
         # Test for existing display manager and disable if necessary
         TestExistingDM
-        # Then enable (included) new DM
+        # Then enable LXDM
         arch_chroot "systemctl enable lxdm.service" >/dev/null
         echo "session=/usr/bin/startlxde" >> /mnt/etc/lxdm/lxdm.conf
         ;;
@@ -310,8 +338,12 @@ then
 fi
 
 if [ -n ${#LuxuriesList[@]} ]; then
-  TPecho "Installing ${LuxuriesList}"
-  pacstrap /mnt ${LuxuriesList}
+  for i in ${LuxuriesList}
+  do
+    TPecho "Installing $i"
+    pacstrap /mnt $i 2> error.log
+    CheckForError "Line ${LINENO} 'Installing $i'" 1
+	done
 fi
 
 EndTime=$(date +%s)
diff --git a/testbed b/testbed
--- a/testbed
+++ b/testbed
@@ -1,129 +1,184 @@
 #!/bin/bash
-
+  
 testbed() {
-
-# MakePartition() {
-  # 1) When selected, first save to AddPartList (eg: /dev/sda5)
-	ExtraPartitions=${#AddPartList[@]}
-	AddPartList[$ExtraPartitions]="${Partition}"
-
-# Experimental move of partition type before partition label
-	CheckPartition   # Before going to select_filesystem, check the partition
-	if [ ${CurrentType} ]; then
-		print_info "You can choose to leave it as it is, by selecting 'Skip', but not"
-		print_info "reformatting an existing partition can have unexpected consequences."
-		echo
-	fi
-	TypeList="ext2 ext3 ext4 btrfs Skip" # Set format types for the selected partition
-	select_filesystem
-	if [ -z ${PartitionType} ]; then
-		PartitionType="Skip"
-	fi
-	AddPartType[$ExtraPartitions]="${PartitionType}" 	# Add it to AddPartType list	
-# End of experiment code move
-	
-  # 2) Then get a label for selected partition (eg: /home)
-	LoopRepeat="Y"
-	while [ ${LoopRepeat} = "Y" ]
-	do
-		print_info "Enter a label for ${Partition} ... eg: '/home' ... "
-		echo
-		TPread "(you must include the '/'): "
-		# Check that entry includes '/'
-		CheckInput=(`echo $Response | cut -c1`)
-		case ${CheckInput} in
-      "") print_info "You must enter a valid name"
-					PartLabel=""
-          ;;
-			*) if [ ${CheckInput} != "/" ]; then
-						PartLabel="/${Response}"
-				else
-						PartLabel="${Response}"
-				fi
-		esac
-		# Check that the label has not already been used
-		LabelCounter=0
-		if [ -z ${AddPartLabel} ]; then
-			LoopRepeat="N"
-		else
-			# Go through AddPartLabel checking each item against PartLabel
-			for Label in ${AddPartLabel}
-			do 
-				LabelCounter=$((LabelCounter+1))
-				if [ $Label = $PartLabel ]; then
-					read_timed "Label ${PartLabel} has already been used. Please use a different label."
-				else
-					LoopRepeat="N"
-					break
-				fi
-			done 
-		fi 
-		if [ ${LoopRepeat} = "N" ]  
-		then
-			break
-		fi 
-	done 
-	AddPartLabel[$ExtraPartitions]="${PartLabel}" 	# Add it to AddPartLabel list
-
+ 
+# AutoPartition() {
+  # This function called from options within Partitioning via MakePartitions
+  AutoPart=1 # Set flag to 'on' for mounting 
+  DiskDetails=`lsblk -l | grep disk | awk '{print $1}'`
+  # DiskDetails="sda sdb" # For testing only ##############################
+  # Count lines. If more than one disk, ask user which to use
+  local Counter=0
+  CountDisks=0
+  for i in $DiskDetails
+  do
+    Counter=$((Counter+1))
+    Drives[$Counter]=$i
+  done
+  if [ $Counter -gt 1 ]
+  then
+    UseDisk=""
+    while [ -z $UseDisk ]
+    do
+      print_heading
+      print_info "There are $Counter devices available"
+      print_info "Which do you wish to use for installation?"
+      print_info "(Remember, this is auto-partition, and any data"
+      print_info "on the chosen device will be lost)"
+      echo
+      Counter=0
+      for i in $DiskDetails
+      do
+        Counter=$((Counter+1))
+        print_info "$Counter) $i"
+      done
+      echo
+      TPread "Enter the number of your selection: "
+      UseDisk="${Drives[$Response]}"
+    done
+  fi
+  GrubDevice="/dev/${UseDisk}"     # "/dev/sda"
+	# Get disk size
+  DiskDetails=`lsblk -l | grep "${UseDisk}\ " | awk '{print $4}' | sed s/G//g`
+  # read -p "$DiskDetails" # For testing only ##############################
+  # Proceed to create partitions and set variables for mounting
+  if [ $UEFI -eq 1 ]; then
+    echo "arch_chroot 'parted /dev/${UseDisk} mklabel gpt'"
+    if [ $DiskDetails -gt 18 ]; then
+      echo "arch_chroot 'parted mkpart ESP fat32 1MiB 1GiB'"
+      EFIPartition="/dev/sda1"
+      echo "arch_chroot 'parted set 1 boot on'"
+      echo "arch_chroot 'parted mkpart primary linux-swap 1GiB 4GiB'"
+      SwapPartition="/dev/sda2"
+      echo "arch_chroot 'parted mkpart primary ext4 4GiB 100%'"
+      RootPartition="/dev/sda3"
+      RootType="ext4"
+    elif [ $DiskDetails -gt 10 ]; then
+      echo "arch_chroot 'parted mkpart ESP fat32 1MiB 1GiB'"
+      EFIPartition="/dev/sda1"
+      echo "arch_chroot 'parted set 1 boot on'"
+      echo "arch_chroot 'parted mkpart primary ext4 1GiB 100%'"
+      RootPartition="/dev/sda2"
+      RootType="ext4"
+      SwapFile="2G"
+      SwapPartition=""
+    else # If disk < 10 Gb
+      echo "arch_chroot 'parted mkpart ESP fat32 1MiB 500MiB'"
+      EFIPartition="/dev/sda1"
+      echo "arch_chroot 'parted set 1 boot on'"
+      echo "arch_chroot 'parted mkpart primary ext4 500MiB 100%'"
+      RootPartition="/dev/sda2"
+      RootType="ext4"
+      SwapFile="2G"
+      SwapPartition=""
+    fi
+  else
+    echo "parted /mnt/dev/${UseDisk} mklabel msdos"
+    if [ $DiskDetails -gt 18 ]; then
+      echo "arch_chroot 'parted mkpart primary linux-swap 1MiB 4GiB'"
+      SwapPartition="/dev/sda1"
+      echo "arch_chroot 'parted mkpart primary ext4 4GiB 100%'"
+      echo "arch_chroot 'parted set 2 boot on'"
+      RootPartition="/dev/sda2"
+      RootType="ext4"
+    elif [ $DiskDetails -gt 10 ]; then
+      echo "arch_chroot 'parted mkpart primary linux-swap 1MiB 2GiB'"
+      SwapPartition="/dev/sda1"
+      echo "arch_chroot 'parted mkpart primary ext4 2GiB 100%'"
+      echo "arch_chroot 'parted set 2 boot on'"
+      RootPartition="/dev/sda2"
+      RootType="ext4"   
+      SwapFile="2G"
+      SwapPartition=""
+    else # If disk < 10 Gb
+      echo "arch_chroot 'parted mkpart primary ext4 1MiB 100%'"
+      echo "arch_chroot 'parted set 1 boot on'"
+      RootPartition="/dev/sda1"
+      RootType="ext4"
+      SwapFile="2G"
+      SwapPartition=""
+    fi
+  fi
+  # Check partitions after creation
+  ShowPartitions=$(lsblk -l | grep 'part' | sed 's/[\t ].*//')
+  Counter=0
+  for i in $ShowPartitions
+  do
+    Counter=$((Counter+1))
+  done
+  PARTITIONS=${Counter}
+  read -p "$PARTITIONS $ShowPartitions" # For testing only ##############################
+ 
 }
-
 
 # ~~~~~~~
 #	Execute
 # ~~~~~~~
-
-# First check for external functions and variables files
-if [[ -f `pwd`/achoovariables ]]; then
-  source achoovariables
-else
-  echo "missing file: achoovariables"
-  exit 1
-fi
-
-if [[ -f `pwd`/achoofuncs ]]; then
-  source achoofuncs
-else
-  echo "missing file: achoofuncs"
-  exit 1
-fi
-
-# Various variables
-RootPartition="sda10"
-RootType="ext4"
-SwapPartition="sda7"
-AddPartList[0]="sda9"
-AddPartLabel[0]="/home"
-AddPartType[0]="ext4"
-AddPartList[1]="sda5"
-AddPartLabel[1]="/spare"
-AddPartType[1]="ext4"
-GrubDevice="/dev/sda"
-CountryCode="GB"
-CountryLocale="en_GB.UTF-8"
-Countrykbd="uk"
-ZONE="Europe"
-SUBZONE="London"
-DesktopEnvironment="xfce4"
-DisplayManager="lightdm"
-Greeter="lightdm-gtk-greeter"
-HostName="ArchLinux"
-RootPassword="Root"
-UserName="archie"
-UserPassword="Linux"
-
-# Call the function 'testbed' holding code to be tested
-testbed
-
-echo "Finished"
-
-exit
-
-# Code for checking arrays
-Counter=0
-for i in ${AddPartList[@]}	
-do
-  echo ${AddPartList[$Counter]}
-  echo ${AddPartLabel[$Counter]} 
-  echo ${AddPartType[$Counter]}
-  Counter=$((Counter+1))
-done
+  
+  # First check for external functions and variables files
+  if [[ -f `pwd`/achoovariables ]]; then
+    source achoovariables
+  else
+    echo "missing file: achoovariables"
+    exit 1
+  fi
+  
+  if [[ -f `pwd`/achoofuncs ]]; then
+    source achoofuncs
+  else
+    echo "missing file: achoofuncs"
+    exit 1
+  fi
+  
+  if [[ -f `pwd`/achoodesktop ]]; then
+    source achoodesktop
+  else
+    echo "missing file: achoodesktop"
+    exit 1
+  fi
+  
+  # Various variables
+  UEFI=1
+  RootPartition="sda10"
+  RootType="ext4"
+  SwapPartition="sda7"
+  PartitionList="sda2 sda3"
+  AddPartList[0]="sda9"
+  AddPartLabel[0]="/home"
+  AddPartType[0]="ext4"
+  AddPartList[1]="sda5"
+  AddPartLabel[1]="/spare"
+  AddPartType[1]="ext4"
+  GrubDevice="/dev/sda"
+  CountryCode="GB"
+  CountryLocale="en_GB.UTF-8"
+  Countrykbd="uk"
+  ZONE="Europe"
+  SUBZONE="London"
+  DesktopEnvironment="xfce4"
+  DisplayManager="lightdm"
+  Greeter="lightdm-gtk-greeter"
+  LuxuriesList="firefox libreoffice-still geany pamac-aur"
+  HostName="ArchLinux"
+  RootPassword="Root"
+  UserName="archie"
+  UserPassword="Linux"
+  DesktopEnvironment="Gnome"
+  
+  # Call the function 'testbed' holding code to be tested
+  testbed
+  echo $* # Add any variables needed for viewing before exit
+  echo "Finished"
+  
+  exit
+  
+  # Code for checking arrays
+  Counter=0
+  for i in ${AddPartList[@]}	
+  do
+    echo ${AddPartList[$Counter]}
+    echo ${AddPartLabel[$Counter]} 
+    echo ${AddPartType[$Counter]}
+    Counter=$((Counter+1))
+  done
+  
